import { useCallback, useEffect, useState } from "react";
import { api, useAuth } from "@/AuthContext";
import { SectionBar, Button, Input, Textarea, Card, CardContent, Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, useUpload, toast, Plus, Upload, Download, downloadFile } from "@/components/erp";
const currencies=["BRL","USD","EUR","GBP","CAD","AUD","JPY","CNY"];
const statuses={ordered:"Pedido",received:"Recebido",paid:"Pago",cancelled:"Cancelado"};
const empty={supplier_id:"",supplier_name:"",product_id:"",product:"",quantity:"",unit:"kg",unit_price:"",total:0,currency:"BRL",date:"",due_date:"",status:"ordered",invoice_number:"",file_path:"",file_name:"",notes:"",track_stock:false,stock_received:false,version:0};
const money=(value,code)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:code||"BRL"}).format(value||0);
const error=e=>typeof e.response?.data?.detail==="string"?e.response.data.detail:"Não foi possível concluir. Recarregue e tente novamente.";
const selectClass="border rounded p-2 bg-white w-full text-sm";
export default function Compras(){
  const {user}=useAuth();
  const [items,setItems]=useState([]),[suppliers,setSuppliers]=useState([]),[products,setProducts]=useState([]),[filter,setFilter]=useState("all"),[currency,setCurrency]=useState("BRL"),[archived,setArchived]=useState(false),[dialog,setDialog]=useState(false),[form,setForm]=useState(empty),[isNew,setIsNew]=useState(false),[saving,setSaving]=useState(false);
  const {el,doUpload,uploading}=useUpload();
  const load=useCallback(()=>api.get("/purchases",{params:{archived}}).then(r=>setItems(r.data)).catch(e=>toast.error(error(e))),[archived]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{api.get("/suppliers").then(r=>setSuppliers(r.data)).catch(e=>toast.error(error(e)));api.get("/products").then(r=>setProducts(r.data)).catch(e=>toast.error(error(e)));},[]);
  const change=(key,value)=>setForm(f=>({...f,[key]:value}));
  const open=p=>{setForm(p?{...empty,...p,stock_received:!!(p.stock_received||p.status==="received")}:{...empty,id:crypto.randomUUID(),date:new Date().toISOString().slice(0,10)});setIsNew(!p);setDialog(true);};
  const save=async()=>{setSaving(true);try{const body={...form,quantity:Number(form.quantity),unit_price:Number(form.unit_price)};if(isNew)await api.post("/purchases",body);else await api.put(`/purchases/${form.id}`,body);setDialog(false);toast.success("Compra salva; financeiro e estoque atualizados.");await load();window.dispatchEvent(new Event("finance-updated"));}catch(e){toast.error(error(e));}finally{setSaving(false);}};
  const archive=async p=>{if(!window.confirm("Arquivar esta compra? Ela poderá ser restaurada em Arquivadas."))return;try{await api.delete(`/purchases/${p.id}`);load();}catch(e){toast.error(error(e));}};
  const restore=async p=>{try{await api.post(`/purchases/${p.id}/restore`);load();toast.success("Compra restaurada");}catch(e){toast.error(error(e));}};
  const filtered=items.filter(p=>(p.currency||"BRL")===currency&&(filter==="all"||p.status===filter));
  const total=filtered.filter(p=>p.status!=="cancelled").reduce((a,p)=>a+(p.total||0),0);
  return <div data-testid="compras-panel">{el}<SectionBar title="Compras" subtitle={`Total em ${currency}: ${money(total,currency)}`} action={<Button onClick={()=>open()} data-testid="new-purchase-button"><Plus className="w-4 h-4 mr-1"/>Nova compra</Button>}/>
    <div className="flex gap-2 mb-4 flex-wrap items-center"><label>Moeda das compras <select aria-label="Moeda das compras" className="border rounded p-2 bg-white" value={currency} onChange={e=>setCurrency(e.target.value)}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label>{[["all","Todas"],...Object.entries(statuses)].map(([k,t])=><Button key={k} variant={filter===k?"default":"outline"} onClick={()=>setFilter(k)}>{t}</Button>)}{user?.role==="admin"&&<Button variant="outline" onClick={()=>setArchived(!archived)}>{archived?"Voltar às ativas":"Arquivadas"}</Button>}</div>
    <div className="space-y-2">{filtered.map(p=><Card key={p.id} data-testid={`purchase-${p.id}`}><CardContent className="p-4 flex flex-wrap items-center gap-3"><span className="text-xs rounded bg-slate-100 p-2">{statuses[p.status]||p.status}</span><div className="flex-1"><strong>{p.product} · {p.quantity} {p.unit}</strong><div className="text-xs">{p.supplier_name} · {p.date} · vence {p.due_date||"—"}</div><div className="text-xs">{p.track_stock?"Estoque próprio":"Entrega pelo fornecedor"} · {p.stock_received?"Mercadoria recebida":"Recebimento pendente"}</div></div><strong>{money(p.total,p.currency)}</strong>{p.file_path&&<Button aria-label={`Baixar anexo de ${p.product}`} variant="ghost" onClick={()=>downloadFile(p.file_path,p.file_name)}><Download className="w-4 h-4"/></Button>}{archived?<Button onClick={()=>restore(p)}>Restaurar</Button>:<><Button variant="outline" onClick={()=>open(p)} data-testid={`edit-purchase-${p.id}`}>Editar</Button>{user?.role==="admin"&&p.status==="cancelled"&&<Button variant="ghost" onClick={()=>archive(p)}>Arquivar</Button>}</>}</CardContent></Card>)}{!filtered.length&&<p data-testid="purchases-empty">Nenhuma compra nesta moeda e situação.</p>}</div>
    <Dialog open={dialog} onOpenChange={v=>{if(!saving&&!uploading)setDialog(v);}}><DialogContent className="bg-white max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Compra</DialogTitle></DialogHeader><div className="grid grid-cols-2 gap-3">
      <label className="col-span-2 text-sm">Fornecedor<select aria-label="Fornecedor da compra" className={selectClass} value={form.supplier_id} onChange={e=>change("supplier_id",e.target.value)}><option value="">Selecione</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
      <label className="col-span-2 text-sm">Produto cadastrado<select aria-label="Produto da compra" className={selectClass} value={form.product_id} onChange={e=>{const p=products.find(x=>x.id===e.target.value);setForm(f=>({...f,product_id:e.target.value,product:p?.name||f.product,unit:p?.unit||f.unit}));}}><option value="">Produto livre (sem entrada em estoque)</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
      {!form.product_id&&<label className="col-span-2 text-sm">Descrição do produto<Input data-testid="pur-product-input" value={form.product} onChange={e=>change("product",e.target.value)}/></label>}
      <label className="text-sm">Quantidade<Input data-testid="pur-qty-input" type="number" min="0" step="any" value={form.quantity} onChange={e=>change("quantity",e.target.value)}/></label><label className="text-sm">Unidade<Input value={form.unit} onChange={e=>change("unit",e.target.value)}/></label>
      <label className="text-sm">Preço unitário<Input data-testid="pur-price-input" type="number" min="0" step="any" value={form.unit_price} onChange={e=>change("unit_price",e.target.value)}/></label><label className="text-sm">Moeda<select aria-label="Moeda da compra" className={selectClass} value={form.currency} onChange={e=>change("currency",e.target.value)}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label>
      <label className="text-sm">Data da compra<Input type="date" value={form.date} onChange={e=>change("date",e.target.value)}/></label><label className="text-sm">Vencimento do pagamento<Input type="date" value={form.due_date} onChange={e=>change("due_date",e.target.value)}/></label>
      <label className="text-sm">Situação<select aria-label="Situação da compra" className={selectClass} value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value,stock_received:f.stock_received||e.target.value==="received"}))}>{Object.entries(statuses).map(([k,t])=><option key={k} value={k}>{t}</option>)}</select></label><strong className="self-center" data-testid="pur-total">Total: {money(Number(form.quantity)*Number(form.unit_price),form.currency)}</strong>
      <label className="text-sm flex gap-2 items-center"><input type="checkbox" checked={form.track_stock} onChange={e=>change("track_stock",e.target.checked)}/>Usar estoque próprio</label><label className="text-sm flex gap-2 items-center"><input type="checkbox" checked={form.stock_received} onChange={e=>change("stock_received",e.target.checked)}/>Mercadoria recebida</label>
      <p className="col-span-2 text-xs">O pagamento e o recebimento da mercadoria são independentes. Só há entrada em estoque ao marcar recebida com estoque próprio e produto cadastrado. Não altera pedidos de venda automaticamente.</p>
      <label className="col-span-2 text-sm">Número da NF (opcional)<Input value={form.invoice_number} onChange={e=>change("invoice_number",e.target.value)}/></label><label className="col-span-2 text-sm">Notas<Textarea value={form.notes} onChange={e=>change("notes",e.target.value)}/></label>
      <Button variant="outline" className="col-span-2" disabled={uploading||saving} onClick={()=>doUpload(file=>setForm(f=>({...f,file_path:file.path,file_name:file.name})))}><Upload className="w-4 h-4 mr-1"/>{form.file_name||(uploading?"Enviando…":"Anexar pedido, NF ou comprovante")}</Button>
    </div><DialogFooter><Button variant="outline" disabled={saving||uploading} onClick={()=>setDialog(false)}>Fechar</Button><Button disabled={saving||uploading} onClick={save} data-testid="save-purchase-button">{saving?"Salvando…":"Salvar"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
