import { useEffect, useMemo, useState } from "react";
import { api } from "@/AuthContext";
import { FolderArchive, FileText, Search, Upload, Trash2, Download, X } from "lucide-react";

const cats=["Financeiro & Fiscal","Produtos","Fornecedores","Clientes & Comercial","Societário","Qualidade & Compliance","Exportação & Logística"];
export default function Documentos(){
 const [docs,setDocs]=useState([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({title:"",category:cats[0],tags:"",notes:"",file:null});
 const load=()=>api.get("/documents").then(r=>setDocs(r.data)).catch(()=>setDocs([]));
 useEffect(load,[]);
 const filtered=useMemo(()=>docs.filter(d=>[d.title,d.category,d.file_name,(d.tags||[]).join(" "),d.notes].join(" ").toLowerCase().includes(q.toLowerCase())),[docs,q]);
 async function submit(e){e.preventDefault(); if(!form.file)return; setBusy(true); try{
   const fd=new FormData(); fd.append("file",form.file); const up=(await api.post("/upload",fd,{headers:{"Content-Type":"multipart/form-data"}})).data;
   await api.post("/documents",{title:form.title||up.name,category:form.category,file_path:up.path,file_name:up.name,content_type:up.content_type,size:up.size,tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean),notes:form.notes});
   setOpen(false); setForm({title:"",category:cats[0],tags:"",notes:"",file:null}); await load();
 }finally{setBusy(false)}}
 async function download(d){const r=await api.get("/files/"+d.file_path,{responseType:"blob"}); const u=URL.createObjectURL(r.data); const a=document.createElement("a");a.href=u;a.download=d.file_name;a.click();URL.revokeObjectURL(u)}
 async function remove(id){if(!window.confirm("Excluir este documento do cadastro?"))return;await api.delete("/documents/"+id);load()}
 return <div className="space-y-6">
  <div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#104496]/45">Gestão documental</p><h1 className="text-3xl font-bold text-[#104496] mt-1">Central de Documentos</h1><p className="text-sm text-slate-500 mt-2">{docs.length} documentos cadastrados.</p></div><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[#104496] text-white text-sm font-semibold"><Upload className="w-4 h-4"/> Novo documento</button></div>
  <div className="relative"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full bg-white border rounded-xl pl-10 pr-4 py-2.5 text-sm" placeholder="Buscar documentos..."/></div>
  <div className="bg-white border rounded-2xl overflow-hidden">{filtered.length===0?<div className="p-8 text-center text-sm text-slate-500"><FolderArchive className="w-8 h-8 mx-auto mb-2"/>Nenhum documento encontrado.</div>:filtered.map(d=><div key={d.id} className="p-4 border-b last:border-0 flex items-center gap-3"><FileText className="w-5 h-5 text-[#104496]"/><div className="min-w-0 flex-1"><div className="font-semibold text-sm text-[#104496] truncate">{d.title}</div><div className="text-xs text-slate-500 truncate">{d.category} · {d.file_name}{d.product_name?` · Produto: ${d.product_name}`:""}{d.supplier_name?` · Fornecedor: ${d.supplier_name}`:""}</div></div><button onClick={()=>download(d)} className="p-2"><Download className="w-4 h-4"/></button><button onClick={()=>remove(d.id)} className="p-2 text-red-600"><Trash2 className="w-4 h-4"/></button></div>)}</div>
  {open&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><form onSubmit={submit} className="bg-white rounded-2xl p-6 w-full max-w-lg space-y-4"><div className="flex justify-between"><h2 className="font-bold text-xl text-[#104496]">Novo documento</h2><button type="button" onClick={()=>setOpen(false)}><X/></button></div><input className="w-full border rounded-xl p-3" placeholder="Título" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select className="w-full border rounded-xl p-3" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{cats.map(x=><option key={x}>{x}</option>)}</select><div className="grid sm:grid-cols-2 gap-3"><select className="w-full border rounded-xl p-3" value={form.product_id} onChange={e=>setForm({...form,product_id:e.target.value})}><option value="">Vincular a produto (opcional)</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="w-full border rounded-xl p-3" value={form.supplier_id} onChange={e=>setForm({...form,supplier_id:e.target.value})}><option value="">Vincular a fornecedor (opcional)</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><input className="w-full border rounded-xl p-3" placeholder="Tags separadas por vírgula" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/><textarea className="w-full border rounded-xl p-3" placeholder="Observações" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><input required type="file" className="w-full" onChange={e=>setForm({...form,file:e.target.files[0]})}/><button disabled={busy} className="w-full bg-[#104496] text-white rounded-xl p-3 font-semibold">{busy?"Enviando...":"Salvar documento"}</button></form></div>}
 </div>
}