import { useCallback, useEffect, useMemo, useState } from "react";
import { api, useAuth } from "@/AuthContext";
import { FolderArchive, Folder, ChevronLeft, FileText, Search, Upload, Trash2, Download, X, Pencil, RotateCcw } from "lucide-react";

const cats=["Financeiro & Fiscal","Produtos","Fornecedores","Clientes & Comercial","Societário","Qualidade & Compliance","Exportação & Logística"];
const sections={pop:"Procedimentos",pop_signed:"Procedimentos assinados",marketing:"Marketing",ibiag_organic:"Certificação orgânica IBIAG"};
const sectionAreas={pop:"Qualidade & Compliance",pop_signed:"Qualidade & Compliance",marketing:"Clientes & Comercial",ibiag_organic:"Qualidade & Compliance"};
const docTypes=["Ficha Técnica","COA / Laudo","Certificado","FISPQ / SDS","Fluxograma","Declaração","Outros"];
const certTypes=["Orgânico","MAPA","Kosher","Halal","FSSC / BRC / ISO","Outros"];
export default function Documentos({defaultSection="",title="Central de Documentos",subtitle="",embedded=false}){
 const {user}=useAuth();const isAdmin=user?.role==="admin";
 const [trash,setTrash]=useState(false),[area,setArea]=useState(""),[sectionFilter,setSectionFilter]=useState(""),[productFolder,setProductFolder]=useState(""),[docTypeFolder,setDocTypeFolder]=useState(""),[certTypeFolder,setCertTypeFolder]=useState(""),[editing,setEditing]=useState(null);
 const [docs,setDocs]=useState([]),[products,setProducts]=useState([]),[suppliers,setSuppliers]=useState([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 const [batchResult,setBatchResult]=useState(""),[preview,setPreview]=useState(null);
 async function linkBatch(e){const file=e.target.files?.[0];e.target.value="";if(!file)return;setBusy(true);try{const fd=new FormData();fd.append("file",file);const r=(await api.post("/documents/link-batch",fd,{headers:{"Content-Type":"multipart/form-data"}})).data;setBatchResult(`${r.documents} documentos vinculados; ${r.offers} ofertas com documentação.`);await load();}catch(err){setBatchResult(err.response?.data?.detail||err.message);}finally{setBusy(false);}}
 async function metadataBatch(e){const file=e.target.files?.[0];e.target.value="";if(!file)return;setBusy(true);try{const fd=new FormData();fd.append("file",file);const r=(await api.post("/documents/metadata-batch",fd,{headers:{"Content-Type":"multipart/form-data"}})).data;const missing=r.not_found_sha256||[];setBatchResult(`${r.updated} documentos reclassificados; ${r.not_found} hashes ainda não encontrados no acervo.`);if(missing.length){const blob=new Blob([JSON.stringify(missing,null,2)],{type:"application/json"});const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download="IBIAG_documentos_nao_encontrados.json";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}await load();}catch(err){setBatchResult(err.response?.data?.detail||err.message);}finally{setBusy(false);}}
 async function importBatch(e){const files=Array.from(e.target.files||[]);e.target.value="";if(!files.length)return;setBusy(true);let imported=0,skipped=0;try{for(const file of files){setBatchResult(`Importando ${file.name}...`);const fd=new FormData();fd.append("file",file);const r=(await api.post("/documents/import-batch",fd,{headers:{"Content-Type":"multipart/form-data"},timeout:180000})).data;imported+=r.imported;skipped+=r.skipped;await load();}setBatchResult(`${imported} documentos importados; ${skipped} duplicatas ignoradas.`);}catch(err){setBatchResult(`${imported} importados até agora. Erro: ${err.response?.data?.detail||err.message}. Você pode reenviar os lotes com segurança.`);await load();}finally{setBusy(false);}}
 const emptyForm={title:"",category:sectionAreas[defaultSection]||cats[0],section:defaultSection,tags:"",notes:"",product_id:"",supplier_id:"",document_type:"",certificate_type:"",folder_path:"",file:null};
 const [form,setForm]=useState(emptyForm);
 const load=useCallback(()=>api.get(trash?"/documents/trash":"/documents",{params:!trash&&defaultSection?{category:defaultSection}:{}}).then(r=>setDocs(r.data)).catch(err=>setBatchResult("Não foi possível carregar os documentos: "+(err.response?.data?.detail||err.message))),[trash,defaultSection]);
 useEffect(()=>{load();},[load]);
 useEffect(()=>{api.get("/products").then(r=>setProducts(r.data)).catch(()=>setProducts([])); api.get("/suppliers").then(r=>setSuppliers(r.data)).catch(()=>setSuppliers([]));},[]);
 const productFolders=useMemo(()=>Array.from(new Set(docs.filter(d=>d.category==="Produtos"&&d.product_name).map(d=>d.product_name))).sort((a,b)=>a.localeCompare(b)),[docs]);
 const folderCount=(cat)=>docs.filter(d=>d.category===cat).length;
 const filtered=useMemo(()=>docs.filter(d=>(!area||d.category===area)&&(!sectionFilter||d.section===sectionFilter)&&(!productFolder||d.product_name===productFolder)&&[d.title,d.category,d.file_name,d.supplier_name,d.product_name,d.document_type,d.certificate_type,d.folder_path,(d.tags||[]).join(" "),d.notes].join(" ").toLowerCase().includes(q.toLowerCase())),[docs,q,area,sectionFilter,productFolder,docTypeFolder,certTypeFolder]);
 async function submit(e){e.preventDefault(); if(!form.file)return; setBusy(true); try{
   const fd=new FormData(); fd.append("file",form.file); const up=(await api.post("/upload",fd,{headers:{"Content-Type":"multipart/form-data"}})).data;
   const product=products.find(x=>x.id===form.product_id), supplier=suppliers.find(x=>x.id===form.supplier_id);
   await api.post("/documents",{title:form.title||up.name,category:form.category,section:form.section,file_path:up.path,file_name:up.name,content_type:up.content_type,size:up.size,tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean),notes:form.notes,product_id:form.product_id||"",product_name:product?.name||"",supplier_id:form.supplier_id||"",supplier_name:supplier?.name||"",document_type:form.document_type||"",certificate_type:form.certificate_type||"",folder_path:form.folder_path||""});
   setOpen(false); setForm(emptyForm); await load();
 }catch(err){setBatchResult("Não foi possível salvar: "+(err.response?.data?.detail||err.message));}finally{setBusy(false)}}
 async function previewFile(d){try{const r=await api.get("/files/"+d.file_path,{responseType:"blob"});setPreview({title:d.title,url:URL.createObjectURL(r.data)});}catch(err){setBatchResult("Não foi possível abrir o documento: "+(err.response?.status||err.message));}}
 function closePreview(){if(preview)URL.revokeObjectURL(preview.url);setPreview(null);}
 async function download(d){const r=await api.get("/files/"+d.file_path,{responseType:"blob"}); const u=URL.createObjectURL(r.data); const a=document.createElement("a");a.href=u;a.download=d.file_name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
 async function remove(id){if(!window.confirm("Mover este documento para a lixeira? O arquivo poderá ser restaurado."))return;try{await api.delete("/documents/"+id);await load();}catch(err){setBatchResult(err.response?.data?.detail||err.message)}}
 async function restore(id){try{await api.post("/documents/"+id+"/restore");await load();}catch(err){setBatchResult(err.response?.data?.detail||err.message)}}
 async function classify(e){e.preventDefault();setBusy(true);try{await api.patch("/documents/"+editing.id+"/classification",{title:editing.title,category:editing.category,section:editing.section||"",notes:editing.notes||"",document_type:editing.document_type||"",certificate_type:editing.certificate_type||"",folder_path:editing.folder_path||""});setEditing(null);await load();}catch(err){setBatchResult(err.response?.data?.detail||err.message)}finally{setBusy(false)}}
 return <div className="space-y-6">
  <div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#104496]/45">Gestão documental</p><h1 className="text-3xl font-bold text-[#104496] mt-1">{title}</h1>{subtitle&&<p className="text-sm text-slate-500 mt-2">{subtitle}</p>}<p className="text-sm text-slate-500 mt-2">{docs.length} {trash?"documentos na lixeira":"documentos cadastrados"}.</p></div>{!embedded&&isAdmin&&<><label className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border text-sm cursor-pointer"><FolderArchive className="w-4 h-4"/>{busy?"Importando...":"Importar lotes PDF"}<input className="hidden" type="file" accept=".zip" multiple disabled={busy} onChange={importBatch}/></label><label className="inline-flex items-center px-4 py-2.5 rounded-xl border text-sm cursor-pointer">Vincular documentos<input className="hidden" type="file" accept=".json" disabled={busy} onChange={linkBatch}/></label><label className="inline-flex items-center px-4 py-2.5 rounded-xl border text-sm cursor-pointer">Reclassificar acervo<input className="hidden" type="file" accept=".json" disabled={busy} onChange={metadataBatch}/></label></>}<button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[#104496] text-white text-sm font-semibold"><Upload className="w-4 h-4"/> Novo documento</button></div>
  {batchResult&&<p role="status" className="text-sm text-[#104496]">{batchResult}</p>}
  <div className="flex gap-3 flex-wrap"><select aria-label="Filtrar área" className="border rounded-xl p-2 text-sm" value={area} onChange={e=>setArea(e.target.value)}><option value="">Todas as áreas</option>{cats.map(c=><option key={c}>{c}</option>)}</select>{!defaultSection&&<select aria-label="Filtrar seção" className="border rounded-xl p-2 text-sm" value={sectionFilter} onChange={e=>setSectionFilter(e.target.value)}><option value="">Todas as seções</option>{Object.entries(sections).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>}{isAdmin&&!embedded&&<button className="border rounded-xl px-3 text-sm" onClick={()=>{setTrash(!trash);setQ("");}}>{trash?"Voltar ao acervo":"Lixeira"}</button>}</div>
  <div className="relative"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full bg-white border rounded-xl pl-10 pr-4 py-2.5 text-sm" placeholder="Buscar documentos..."/></div>
  {!trash&&!q&&<div className="space-y-3">
    {(area||productFolder||docTypeFolder||certTypeFolder)&&<button className="inline-flex items-center gap-2 text-sm text-[#104496] font-semibold" onClick={()=>{if(certTypeFolder){setCertTypeFolder("");}else if(docTypeFolder){setDocTypeFolder("");setCertTypeFolder("");}else if(productFolder){setProductFolder("");setDocTypeFolder("");}else{setArea("");setSectionFilter("");setDocTypeFolder("");setCertTypeFolder("");}}}><ChevronLeft className="w-4 h-4"/>Voltar</button>}
    {!area&&<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{cats.map(cat=><button key={cat} onClick={()=>{setArea(cat);setProductFolder("");setDocTypeFolder("");setCertTypeFolder("");}} className="text-left bg-white border rounded-2xl p-4 hover:border-[#104496]/40 hover:shadow-sm transition"><Folder className="w-7 h-7 text-[#104496] mb-3"/><div className="font-semibold text-[#104496]">{cat}</div><div className="text-xs text-slate-500 mt-1">{folderCount(cat)} documentos</div></button>)}</div>}
    {area==="Produtos"&&!productFolder&&productFolders.length>0&&<div><div className="text-xs font-semibold uppercase tracking-widest text-[#104496]/50 mb-2">Subpastas · Produtos</div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{productFolders.map(name=><button key={name} onClick={()=>setProductFolder(name)} className="text-left bg-white border rounded-2xl p-4 hover:border-[#104496]/40 hover:shadow-sm transition"><Folder className="w-6 h-6 text-[#104496] mb-2"/><div className="font-semibold text-[#104496]">{name}</div><div className="text-xs text-slate-500 mt-1">{docs.filter(d=>d.category==="Produtos"&&d.product_name===name).length} documentos</div></button>)}</div></div>}
    {area&&!docTypeFolder&&availableDocTypes.length>0&&<div><div className="text-xs font-semibold uppercase tracking-widest text-[#104496]/50 mb-2">Subpastas · Tipo de documento</div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{availableDocTypes.map(name=><button key={name} onClick={()=>{setDocTypeFolder(name);setCertTypeFolder("");}} className="text-left bg-white border rounded-2xl p-4 hover:border-[#104496]/40 hover:shadow-sm transition"><Folder className="w-6 h-6 text-[#104496] mb-2"/><div className="font-semibold text-[#104496]">{name}</div><div className="text-xs text-slate-500 mt-1">{scopeDocs.filter(d=>d.document_type===name).length} documentos</div></button>)}</div></div>}
    {area&&docTypeFolder==="Certificado"&&!certTypeFolder&&availableCertTypes.length>0&&<div><div className="text-xs font-semibold uppercase tracking-widest text-[#104496]/50 mb-2">Subpastas · Certificados</div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{availableCertTypes.map(name=><button key={name} onClick={()=>setCertTypeFolder(name)} className="text-left bg-white border rounded-2xl p-4 hover:border-[#104496]/40 hover:shadow-sm transition"><Folder className="w-6 h-6 text-[#104496] mb-2"/><div className="font-semibold text-[#104496]">{name}</div><div className="text-xs text-slate-500 mt-1">{scopeDocs.filter(d=>d.document_type==="Certificado"&&d.certificate_type===name).length} documentos</div></button>)}</div></div>}
    {area&&<div className="text-xs text-slate-500">Documentos / <b>{area}</b>{productFolder&&<span> / <b>{productFolder}</b></span>}{docTypeFolder&&<span> / <b>{docTypeFolder}</b></span>}{certTypeFolder&&<span> / <b>{certTypeFolder}</b></span>}</div>}
  </div>}
  {(!(!trash&&!q)||area||productFolder||docTypeFolder||certTypeFolder)&&<div className="bg-white border rounded-2xl overflow-hidden">{filtered.length===0?<div className="p-8 text-center text-sm text-slate-500"><FolderArchive className="w-8 h-8 mx-auto mb-2"/>Nenhum documento encontrado.</div>:filtered.map(d=><div key={d.id} className="p-4 border-b last:border-0 flex items-center gap-3"><FileText className="w-5 h-5 text-[#104496]"/><div className="min-w-0 flex-1"><div className="font-semibold text-sm text-[#104496] truncate">{d.title}</div><div className="text-xs text-slate-500 truncate">{d.category}{d.folder_path?` · ${d.folder_path}`:""}{d.document_type?` · ${d.document_type}`:""}{d.certificate_type?` · ${d.certificate_type}`:""}{d.section?` · ${sections[d.section]||d.section}`:""} · {d.file_name}{d.product_name?` · Produto: ${d.product_name}`:""}{d.supplier_name?` · Fornecedor: ${d.supplier_name}`:""}</div></div><button aria-label={`Visualizar ${d.title}`} onClick={()=>previewFile(d)} className="p-2"><FileText className="w-4 h-4"/></button><button aria-label={`Baixar ${d.title}`} onClick={()=>download(d)} className="p-2"><Download className="w-4 h-4"/></button>{isAdmin&&(trash?<button aria-label={`Restaurar ${d.title}`} onClick={()=>restore(d.id)} className="p-2"><RotateCcw className="w-4 h-4"/></button>:<><button aria-label={`Classificar ${d.title}`} onClick={()=>setEditing(d)} className="p-2"><Pencil className="w-4 h-4"/></button><button aria-label={`Excluir ${d.title}`} onClick={()=>remove(d.id)} className="p-2 text-red-600"><Trash2 className="w-4 h-4"/></button></>)}</div>)}</div>}
  {preview&&<div className="fixed inset-0 z-50 bg-black/50 p-4 flex flex-col"><div className="bg-white rounded-t-xl p-3 flex justify-between items-center"><span className="font-semibold text-[#104496]">{preview.title}</span><button aria-label="Fechar visualização" onClick={closePreview}><X/></button></div><iframe title={preview.title} src={preview.url} className="w-full flex-1 bg-white rounded-b-xl"/></div>}
  {open&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><form onSubmit={submit} className="bg-white rounded-2xl p-6 w-full max-w-lg space-y-4"><div className="flex justify-between"><h2 className="font-bold text-xl text-[#104496]">Novo documento</h2><button type="button" onClick={()=>setOpen(false)}><X/></button></div><input className="w-full border rounded-xl p-3" placeholder="Título" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select className="w-full border rounded-xl p-3" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{cats.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Seção do documento" className="w-full border rounded-xl p-3" value={form.section} onChange={e=>setForm({...form,section:e.target.value,category:sectionAreas[e.target.value]||form.category})}><option value="">Classificação automática por tipo</option>{Object.entries(sections).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><div className="grid sm:grid-cols-2 gap-3"><select className="w-full border rounded-xl p-3" value={form.product_id} onChange={e=>setForm({...form,product_id:e.target.value})}><option value="">Vincular a produto (opcional)</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="w-full border rounded-xl p-3" value={form.supplier_id} onChange={e=>setForm({...form,supplier_id:e.target.value})}><option value="">Vincular a fornecedor (opcional)</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="grid sm:grid-cols-2 gap-3"><select aria-label="Tipo de documento" className="w-full border rounded-xl p-3" value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value})}><option value="">Tipo de documento</option>{docTypes.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Tipo de certificado" className="w-full border rounded-xl p-3" value={form.certificate_type} onChange={e=>setForm({...form,certificate_type:e.target.value})}><option value="">Tipo de certificado</option>{certTypes.map(x=><option key={x}>{x}</option>)}</select></div><input className="w-full border rounded-xl p-3" placeholder="Pasta / subpasta (ex.: Produtos/Acerola/COA)" value={form.folder_path} onChange={e=>setForm({...form,folder_path:e.target.value})}/><input className="w-full border rounded-xl p-3" placeholder="Tags separadas por vírgula" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/><textarea className="w-full border rounded-xl p-3" placeholder="Observações" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><input required type="file" className="w-full" onChange={e=>setForm({...form,file:e.target.files[0]})}/><button disabled={busy} className="w-full bg-[#104496] text-white rounded-xl p-3 font-semibold">{busy?"Enviando...":"Salvar documento"}</button></form></div>}
  {editing&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><form onSubmit={classify} className="bg-white rounded-2xl p-6 w-full max-w-lg space-y-4"><h2 className="text-xl font-bold">Classificar documento</h2><input required aria-label="Título do documento" className="w-full border rounded-xl p-3" value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/><select aria-label="Área do documento" className="w-full border rounded-xl p-3" value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}>{cats.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Seção do documento" className="w-full border rounded-xl p-3" value={editing.section||""} onChange={e=>setEditing({...editing,section:e.target.value})}><option value="">Classificação automática por tipo</option>{Object.entries(sections).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><div className="grid sm:grid-cols-2 gap-3"><select aria-label="Tipo de documento" className="w-full border rounded-xl p-3" value={editing.document_type||""} onChange={e=>setEditing({...editing,document_type:e.target.value})}><option value="">Tipo de documento</option>{docTypes.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Tipo de certificado" className="w-full border rounded-xl p-3" value={editing.certificate_type||""} onChange={e=>setEditing({...editing,certificate_type:e.target.value})}><option value="">Tipo de certificado</option>{certTypes.map(x=><option key={x}>{x}</option>)}</select></div><input aria-label="Pasta do documento" className="w-full border rounded-xl p-3" placeholder="Pasta / subpasta" value={editing.folder_path||""} onChange={e=>setEditing({...editing,folder_path:e.target.value})}/><textarea aria-label="Observações do documento" className="w-full border rounded-xl p-3" value={editing.notes||""} onChange={e=>setEditing({...editing,notes:e.target.value})}/><div className="flex gap-3"><button type="button" onClick={()=>setEditing(null)}>Cancelar</button><button disabled={busy} className="rounded-xl bg-[#104496] text-white px-4 py-2">{busy?"Salvando...":"Salvar classificação"}</button></div></form></div>}
 </div>
}
