import { useEffect, useState } from "react";
import { api, useAuth } from "@/AuthContext";
import { PageHeader, Button, Input, Card, CardContent, toast } from "@/components/erp";
export default function Inventory(){
  const {user}=useAuth();
  const [items,setItems]=useState([]),[edits,setEdits]=useState({}),[busy,setBusy]=useState(null),[query,setQuery]=useState("");
  const load=()=>api.get("/products").then(r=>setItems(r.data)).catch(()=>toast.error("Não foi possível carregar o estoque."));
  useEffect(()=>{load();},[]);
  const update=async id=>{const raw=edits[id];if(raw===undefined||raw.trim()==="")return toast.error("Informe a quantidade física.");const value=Number(raw);if(!Number.isFinite(value)||value<0)return toast.error("Quantidade deve ser zero ou maior.");setBusy(id);try{await api.patch(`/products/${id}/stock`,{stock:value});toast.success("Estoque físico ajustado");setEdits(x=>({...x,[id]:""}));load();}catch(e){toast.error(e.response?.data?.detail||"Não foi possível ajustar.");}finally{setBusy(null);}};
  return <div data-testid="inventory-page"><PageHeader number="07 · Estoque" title="Estoque" subtitle="Saldo físico, reservas de pedidos confirmados e quantidade disponível"/><p className="text-sm mb-4">Compras recebidas acrescentam ao saldo; pedidos embarcados descontam uma vez. Entregas diretas pelo fornecedor não movimentam este estoque. O ajuste manual informa o saldo físico atual.</p><Input aria-label="Buscar produto no estoque" placeholder="Buscar produto ou SKU" value={query} onChange={e=>setQuery(e.target.value)} className="mb-4"/><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{items.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(query.toLowerCase())).map(p=><Card key={p.id}><CardContent className="p-4"><strong>{p.name}</strong><p className="text-xs">SKU: {p.sku||"—"} · {p.unit}</p><div className="grid grid-cols-3 gap-2 text-sm my-3"><div>Físico<br/><strong>{p.stock||0}</strong></div><div>Reservado<br/><strong>{p.stock_reserved||0}</strong></div><div>Disponível<br/><strong>{p.stock_available??p.stock??0}</strong></div></div>{user?.role==="admin"&&<div className="flex gap-2"><Input aria-label={`Novo saldo físico de ${p.name}`} type="number" min="0" step="any" placeholder="Saldo físico atual" value={edits[p.id]??""} onChange={e=>setEdits(x=>({...x,[p.id]:e.target.value}))} data-testid={`stock-input-${p.id}`}/><Button disabled={busy!==null} onClick={()=>update(p.id)} data-testid={`update-stock-${p.id}`}>{busy===p.id?"Salvando…":"Ajustar"}</Button></div>}</CardContent></Card>)}</div></div>;
}
